schema_version = "1.0.0"
id = "sidequest_banter_avatars"
name = "Banter Avatar Configurator"
version = "0.2.0"
tagline = "Configure and upload custom avatars for the Bantaverse"
maintainer = "SideQuest"
type = "add-on"
permissions = { files = "Export glTF avatars", network = "Upload avatars to Banter" }
tags = ["Import-Export", "Modeling"]
blender_version_min = "4.2.0"
license = ["SPDX:MIT"]
website = "https://github.com/SideQuestVR/banter-blender-plugin"
copyright = ["2024 SideQuest VR Ltd"]
