name: Publish Extensions
on:
  push:
    branches:
      - "gh-actions"
    # tags:
    #   #- '[a-zA-Z-_]+\/[0-9]+\.[0-9]+\.[0-9]+' # Generic match for subproject/x.y.z
    #   - 'avatars\/[0-9]+\.[0-9]+\.[0-9]+' # Specific for avatars/x.y.z

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Blender and package addon
        uses: moguri/setup-blender@v1
        with:
          blender-version: '4.2'

      - name: Validate
        run: |
          # cd $GITHUB_WORKSPACE/addons/banter_avatar_plugin
          blender --command extension validate $GITHUB_WORKSPACE/addons/banter_avatar_plugin
          blender --command extension build --source-dir $GITHUB_WORKSPACE/addons/banter_avatar_plugin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: $GITHUB_WORKSPACE/sidequest_banter_avatars-1.0.0.zip
          name: sidequest_banter_avatars
          

    #   - name: Publish artifact
    #     run: |
    # 	  # Add publish commands here
